version: 2.1

executors:
  machine_dlc:
    machine:
      image: ubuntu-2204:2023.02.1
      docker_layer_caching: true

jobs:
  image_pull:
    parameters:
      docker_image:
        type: string
    executor:
      machine_dlc
    steps:
      # check what images were saved by "previous DLC"
      - run: |
          docker image ls
      - checkout
      - run: |
          docker image pull << parameters.docker_image >>
      - run: |
          docker image ls

workflows:
  main:
    jobs:
      - image_pull:
          matrix:
            parameters:
              docker_image:
                # approx 1.12 GB
                - "cimg/base:current"
                # approx 2.09 GB
                - "cimg/mysql:5.7"
