version: 2.1

executors:
  machine_dlc:
    machine:
      image: ubuntu-2204:2023.02.1
      docker_layer_caching: true

jobs:
  image_build:
    parameters:
      dockerfile:
        type: string
    executor:
      machine_dlc
    steps:
      - checkout
      - run: |
          docker image build --tag test --file << parameters.dockerfile >> .
      - run: |
          docker image ls

workflows:
  main:
    jobs:
      - image_build:
          matrix:
            parameters:
              dockerfile:
                # intermediate (16gb) -> final (16gb)
                - Dockerfile_16gb_16gb
                # intermediate (13gb) -> final (16gb)
                - Dockerfile_13gb_16gb
